name: Deploy to EC2 with Dockerfile

on:
  push:
    branches:
      - deploy-with-dockerfile  # Esta rama activa el flujo de trabajo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        # Construir la imagen de Docker y etiquetarla como 'latest'
        docker build -t ${{ secrets.DOCKER_USERNAME }}/aws:latest .

        # Empujar la imagen a Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/aws:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Detener y remover el contenedor existente
          sudo docker rm -f web || true

          # Limpiar imágenes de Docker no utilizadas
          sudo docker image prune -f || true

          # Descargar la última imagen desde Docker Hub
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/aws:latest

          # Ejecutar el contenedor actualizado
          sudo docker run -d -p 80:80 --name web \
            -v /home/ubuntu/pageaws/index.html:/usr/share/nginx/html/index.html \
            ${{ secrets.DOCKER_USERNAME }}/aws:latest

          echo "¡Deploy App from Docker Hub!"
        EOF
