name: Deploy to EC2 from Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/aws:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/aws:latest

    - name: SSH into EC2 and pull the latest Docker image
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER 
          sudo systemctl restart docker  

          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/aws:latest
          sudo docker stop $(docker ps -q) || true
          sudo docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/aws:latest
